name: proto_checks

on: [pull_request]

jobs:
  proto_checks:
    name: proto lint, breaking changes detection and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - uses: arduino/setup-protoc@v2
        with:
          version: '21.9'

      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Generating protos
        run: |
          protoc --proto_path=api/$PROTO_DIR api/$PROTO_DIR/proto/*.proto --go_out=api/$PROTO_DIR/protobuf --go-grpc_out=api/$PROTO_DIR/protobuf
        env:
          PROTO_DIR: users